version: "3"
services:

  xsonic-db:
    image: postgres:15
    container_name: xsonic-db
    restart: always
    networks:
      - xsonic-network

    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
 
  xsonic-api:
    build: './xsonic-api'
    container_name: xsonic-api
    depends_on:
      - xsonic-db
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - API_SECRET=${API_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - AMAZON_ACCESS_KEY=${AMAZON_ACCESS_KEY}
      - AMAZON_SECRET_KEY=${AMAZON_SECRET_KEY}
      - AMAZON_S3_BUCKET_NAME=${AMAZON_S3_BUCKET_NAME}
    networks:
      - xsonic-network
    ports:
      - ${SERVER_PORT}:8888

  xsonic-ui:
    build: './xsonic-ui'
    container_name: xsonic-ui
    depends_on:
      - xsonic-api
    networks:
      - xsonic-network
    ports:
      - 3000:3000

networks:
  xsonic-network:
    driver: bridge