spring:
  application:
    name: xsonic
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:xsonic}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql
    maxActive: 3

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID:1153f68a72318896d4d6}
            clientSecret: ${GITHUB_CLIENT_SECRET:dad649876e973a2010c4d5089c6513dbd0a1cc07}
            scope: read:user, user:email
          google:
            clientId: ${GOOGLE_CLIENT_ID:452294761260-c38fh0tjbumc3abspj8khd8qnvlv2vri.apps.googleusercontent.com}
            clientSecret: ${GOOGLE_CLIENT_SECRET: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}
            scope: profile, email

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME:saddolgov@gmail.com}
    password: ${MAIL_PASSWORD:hwpsvefofibyxvcr}
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
  flyway:
    locations: classpath:db/migration

app:
  jwt:
    header: Authorization
    # Signing key for HS512 algorithm
    # In https://it-tools.tech/token-generator you can generate all kinds of keys
    secret: ${API_SECRET:KBsbQQzk/ywupPhUIisr{bad:r08qLvetdu#ZX:i-Lu)K-jS@WJwmOl6g-\ods+s}
    expiration:
        minutes: 60
  oauth2:
    redirectUri: ${REDIRECT_URI:http://localhost:3000/oauth2/redirect}
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}

upload:
  path: classpath:images

amazon:
  aws:
    access-key: ${AMAZON_ACCESS_KEY:AKIATP4TDBGPCTXUIXD2}
    secret-key: ${AMAZON_SECRET_KEY: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}
  s3:
    bucket:
      name: ${AMAZON_S3_BUCKET_NAME:xsonicwebstore}



recaptcha:
  secret: 6Lc5cLkZAAAAANUjd4--Jx6PioSC_N-9MFKT3PsA
  url: https://www.google.com/recaptcha/api/siteverify?secret=%s&response=%s

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

emailConfirmation: false

mail:
  debug: false

server:
  port: ${SERVER_PORT:8888}